### PR TITLE
Add .prettier config file

### LINKED ISSUE #4: Error when creating a new project: ERR_INVALID_ARG_TYPE
Tried to initialize a new managed component using

```
npm init managed-component
```

```
OS: Windows 10
Node: v18.1.0
npm: 8.11.0
create-managed-component: 1.0.10
```

Full error and input:

```
√ Display name: ... test-mc
√ Description: ... just a test
√ Path to svg icon: ... assets/icon.svg
√ Requested Permissions: »
√ Confirm new managed component?: {
  "displayName": "test-mc",
  "description": "just a test",
  "icon": "assets/icon.svg",
  "permissions": {}
} ... yes
node:internal/errors:466
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.mkdirSync (node:fs:1350:10)
    at exports.default (C:\Users\adamg\AppData\Local\npm-cache\_npx\b98a785dcc98b45a\node_modules\create-managed-component\dist\renderTemplate.js:13:22)
    at C:\Users\adamg\AppData\Local\npm-cache\_npx\b98a785dcc98b45a\node_modules\create-managed-component\dist\index.js:222:38
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### PR DESCRIPTION
**Pull request by BlueFrog130**
Closes #4

### CODE REVIEW

**Comment by BlueFrog130** [comment]
Also added `.prettierrc`, but that was mainly so my VS Code wouldn't auto format

**Comment by bjesus** [comment]
Hey @BlueFrog130 , thanks for sending this! I decided to fix this namespace issue by explicitly asking for it, even if the display name is good enough: https://github.com/managed-components/create-managed-component/commit/bc115d5b55bb23f6577936c8cfe3b490933f3ed8 

If you can remove that part of the PR, I'm happy to merge the Prettier settings because I was just hit but the automatic formatting too.

**Comment by BlueFrog130** [comment]
> Hey @BlueFrog130 , thanks for sending this! I decided to fix this namespace issue by explicitly asking for it, even if the display name is good enough: [bc115d5](https://github.com/managed-components/create-managed-component/commit/bc115d5b55bb23f6577936c8cfe3b490933f3ed8)
> 
> If you can remove that part of the PR, I'm happy to merge the Prettier settings because I was just hit but the automatic formatting too.

@bjesus 

Dropped that commit.

Also, I created a JSON schema for the manifest file to provide some intellisense, but that may be better suited for managed-components/types

**Comment by bjesus** [comment]
Merged.

If you think the intellisense stuff makes more sense on `types`, let's add it there!

**Pull request merged**
